### ISSUE TITLE
Pan, tilt and zoom functionality in perspective images

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#112]
Pan, tilt and zoom are supported in both panoramas and perspective images. The features are only enabled in panoramas because the pan and tilt needs to be restricted in perspective images to avoid showing to much void. This needs to be handled by a class / component that knows about the render camera. When the restriction for pan and tilt is implemented the zooming in perspective images can be turned on.

**Comment by pbb72** [comment]
In first instance, we need a very simple pixel-zoom for regular photos. No complicated perspective and tilt compensation, just enlarging the individual pixels.

The reason for this is being able to zoom into details that are not visible in the scaled-down view that is presented on the website. This is especially vital in the blur editor, since license plates and faces may not be visible in the editor while they may be visible in downloaded photos.

**Comment by oscarlorentzon** [comment]
Yes, that is basically what this issue is about. Making it possible to zoom in to enlarge the photo pixels in view. 

Agree that the functionality is most important for the blur editing.

**Comment by pbb72** [comment]
Wooohoo fantastic! This is such a cool way to pan the photos! :smile:

Very well done @oscarlorentzon!

**Comment by de-vries** [comment]
very nice, this is the best feature added since the new site!
