### ISSUE TITLE
Tweak the build process

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary-js#114]
- [x] Faster `npm prepublish`
- [x] Replace documentation scripts (`typedoc` is currently broken with `typescript@1.7+`)
- [ ] Generate `*.d.ts` files
- [x] Remove BrowserSync
- [x] `watch` reloads the bundled file
- [x] Lint before commit

Related #71, #87, #100

**Comment by oscarlorentzon** [comment]
Things I would appreciate if the tweaks could solve:

* Single build by default (e.g. `gulp ts` instead of what `gulp ts --env=TEST` is now).
* As few dev dependencies as possible. Right now we depend on a lot of `gulp` plugins wrapping `typescript` functionality. We always want to develop off the latest `typescript` version. This requires someone to constantly update the `gulp` plugins. Staying as close to the `typescript` tools as possible ensures that we do not depend on other tools being updated in the same pace.
* Removal of BrowserSync. Right now it adds no value for me in the development process. It is also not possible to spin up two viewers in different browsers without them affecting each other when navigating. 
* When rebuilding during `watch` I would appreciate that the automatic browser reload loaded the rebuilt bundle.js file. As it is now one needs to reload the browser manually one or two times after the automatic reload for the changes to take effect.

**Comment by knikel** [comment]
@oscarlorentzon Thanks for the comments. I've updated the task list in the first message in this issue.

**Comment by oscarlorentzon** [comment]
Documentation scripts updated in 1d92a83a48fc1aa0b421a0bea4fad8be1d33b4d4.

**Comment by oscarlorentzon** [comment]
Generate type definitions files with be handled in #87
