### ISSUE TITLE
Merge Sequence and Player components and restyle

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#122]
The `Sequence` and `Player` components have been merged in the latest design proposals from @angelday in #96:

![screen shot 2016-05-04 at 15 25 53](https://cloud.githubusercontent.com/assets/50189/15015492/8237de84-120c-11e6-82f4-767e95b47dbf.png)

This design requires architectural changes of the `Sequence` and `Player` components. They need to be merged to a single component. 

- [x] Create design for `Sequence`/`Player` component
- [x] Merge `Sequence` and `Player` components and name it `SequenceComponent`
- [x] Add a `sequence` directory in the `components` directory
- [x] Move code related to DOM rendering to a SequenceDOMRenderer class
- [x] Implement style according to design

**Comment by oscarlorentzon** [comment]
@angelday Can you confirm that the `Sequence`/`Player` item is the final design?

**Comment by angelday** [comment]
@oscarlorentzon Yes, we're building this. I put the assets to https://github.com/mapillary/mapillary-js/issues/68

Note the spatial controls will have to be redesigned according to the exhibit, please check with me when you're there.

Not sure if it belongs here, but the ℰ𝓁𝓋𝒶 sequence steppers have to be smaller in order to fit the map view component 100% view:

![screen shot 2016-05-16 at 10 37 31](https://cloud.githubusercontent.com/assets/50189/15284552/3bde32fe-1b52-11e6-849e-6cd05f8ea465.png)

Reassigning.

**Comment by oscarlorentzon** [comment]
@angelday: When playing is started there needs to be a stop button. Should the play button change into a stop button when playing?

**Comment by angelday** [comment]
Yes, I'll provide

**Comment by angelday** [comment]
Prepared it:

![screen shot 2016-05-24 at 11 55 21](https://cloud.githubusercontent.com/assets/50189/15499980/fae73146-21a6-11e6-842b-c54519af41cc.png)

Shared in Zeplin:

![screen shot 2016-05-24 at 11 59 03](https://cloud.githubusercontent.com/assets/50189/15499982/fd42da76-21a6-11e6-9852-339903b9f0f1.png)

@oscarlorentzon invited you to the project in Zeplin.

**Comment by oscarlorentzon** [comment]
Dynamic resizing will be handled in #128

**Comment by oscarlorentzon** [comment]
Handing over the styling task to you @knikel.
