### ISSUE TITLE
Moible view without WebGL incorrect

### ISSUE THREAD

**Issue by peterneubauer** [mapillary/mapillary-js#162]
![screenshot_2016-07-20-05-49-17](https://cloud.githubusercontent.com/assets/11977/16986896/6a374464-4e89-11e6-90df-9ceb187892e5.png)

**Comment by oscarlorentzon** [comment]
The image component seems to render the image correctly.

The fact that the spatial navigation arrows are not rendered correctly is not related to WebGL / no WebGL support. It seems like the browser does not support CSS transforms. 

For that there is another component called `navigation` that could potentially be used instead of the `direction` one.

**Comment by oscarlorentzon** [comment]
Closing as this will be handled in #177
