### ISSUE TITLE
Add LABEL.md

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#173]
That describes the meaning of different labels.

Seems like you should be able to clean the labels up a bit to. There are a lot of them thats not attached to any issue.

**Comment by oscarlorentzon** [comment]
Changed the label structure to be similar to [mapillary/mapillary_issues/labels](https://github.com/mapillary/mapillary_issues/labels). I do not think that there is a need for a LABEL.md file in this repository because the labels should be self explaining and the labelling is more important for reporters in [mapillary/mapillary_issues](https://github.com/mapillary/mapillary_issues).

Is it OK if I close this issue @gyllen?

**Comment by gyllen** [comment]
Closing, nice update
