### ISSUE TITLE
Navigation component without CSS transformations

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#177]
Make it possible to navigate on devices not supporting CSS transforms by removing those while keeping functionality in `Navigation` component.

Related to #162

**Comment by knikel** [comment]
I think we should decide what browsers to support really. Most of the modern browser would support that. In #162 the problem might lay with lack of prefixes on`vdom` nodes, which `autoprefixer` doesn't catch (since it's not parsing `.ts`/`.js` files).  Would having a function that renders transformation syntax with prefixes solve that?

**Comment by oscarlorentzon** [comment]
The navigation component sets all the styles in CSS (not `vdom`) so the autoprefixer should handle prefixes there. Seems like some Android browsers does not support `transform` even with all the correct prefixes. Need information from @peterneubauer or @rsahlin about Android browser compatibility regarding CSS prefixes for transform and what we need to support.
