### ISSUE TITLE
put each new release to webjars.org, too

### ISSUE THREAD

**Issue by hakan42** [mapillary/mapillary-js#193]
Whenever a new release is created, go to webjars.org and create a new package there, too.
1. go to http://www.webjars.org/npm
2. in the search field, type "mapillary"
3. select the just created new version and create a webjar too
### Expected Behavior

The consumer can use the webjars, for example in spring-boot based projects
### Actual Behavior

An user, as of yet me :smile: , goes to webjars.org and creates the webjar packages whenever I notice a new release mail from github :smiling_imp:

**Comment by oscarlorentzon** [comment]
Thanks for the interest @hakan42. I have tried your suggestion of deploying new versions in webjars and it works fine. Because of my limited knowledge about webjars and the tool in general I think it would work best as a community effort though. Whenever someone wants to use the latest version she/he can always just deploy it.

**Comment by oscarlorentzon** [comment]
Closing for the reasons explained above.
