### ISSUE TITLE
Image tiling causes wrong aspect ratio of rendered texture on certain system

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#253]
**mapillary-js version**: 2.5
**OS**: Ubuntu 16.04
**Browser**: Chrome
**GL max texture size**: 8192

### Steps to Reproduce Behavior

 1. Go to an image with width or height larger than 4096
 2. Zoom in

### Expected Behavior
Higher resolution tiles are loaded and rendered on top of the original image in the right position

### Actual Behavior
Image tiles are scaled down on the axis that is larger than 4096 pixels causing the aspect ratio of the tiles to be wrong. The wrongly scaled tiles are rendered from the top left corner of the render target causing a black area at the right or bottom of the texture.

### Additional information
This does not happen on Firefox in Ubuntu 16.04 and it is not possible to reproduce on IE11, Chrome, Edge or Firefox on Windows or Safari, Firefox and Chrome on OSX (max texture size 16384).

**Comment by gerhardneuhold** [comment]
After upgrading the NVIDIA driver to version `375.66` this issue got resolved on my laptop. Upgrade was done using `apt-get upgrade nvidia-375` which automatically upgraded OpenGL libraries too.

Interestingly, the reported GL max texture size is now 16384 instead of previously 8192 using [1].

[1] https://www.khronos.org/registry/webgl/sdk/tests/conformance/limits/gl-max-texture-dimensions.html

**Comment by oscarlorentzon** [comment]
Closing with no action required in MJS.
