### ISSUE TITLE
Add Viewer.project method for symmetry

### ISSUE THREAD

**Issue by oscarlorentzon** [mapillary/mapillary-js#296]
The Viewer class has [projectFromBasic](https://mapillary.github.io/mapillary-js/classes/viewer.html#projectfrombasic), [unprojectToBasic](https://mapillary.github.io/mapillary-js/classes/viewer.html#unprojecttobasic), and [unproject](https://mapillary.github.io/mapillary-js/classes/viewer.html#unproject) methods. 

The API would be symmetric if a `project` method is added. It would need to handle `latLons` to far away from the current node. 

If the API would be added all conversions between pixel, basic, and latLon coordinates back and forth would be possible.

**Comment by mrAceT** [comment]
I can't wait until you have implemented this!

If I may add a few extra ideas (when you're going to dive into the matter anyway ;) )

**1) option: one-point perspective**
When a line is drawn from one lat/lon to another the visual effect would be awesome because it would add greatly to the illusion of depth
**2) option: float (from/to)**
Start with "plus one meter" (maybee even two?) at point of view and drop to zero (or maybe even minus one?) at the horizon.

AD 2)
To my regret Mapillary does not handle altitude (I do add it to the EXIF in my 360-images if one ever wants to test!). Usually SfM does a very nice job correcting the images (lat/lon, horizon & bearing) , but perfection is tough... I am testing with "MarkerComponent.CircleMarker" to place SfM positions in view, but when the horizon isn't perfect the effect of the path goes "up into the sky". Which is visually disappointing.. On the other hand when I look the other way in that 360 image the visual effect of the dots "going into the ground" is optically quite acceptable!

Example:
I am working on a viewer for a personal project, it is still very much a work in progress and the page will crash eventually due to overload (memory and such..) and this works best on a desktop computer

The crocked image:
https://www.geoarchief.nl/mapillary6.html?key=UQWEcuJldoChe55mCYRzvw&x=.75&y=.5&zoom=.1
When you turn left 90 degrees it looks very much OK:
https://www.geoarchief.nl/mapillary6.html?key=UQWEcuJldoChe55mCYRzvw&x=.5&y=.5&zoom=.1
When you turn left 180 degrees (and 270 also) it brings a tear of sadness to my eye:
https://www.geoarchief.nl/mapillary6.html?key=UQWEcuJldoChe55mCYRzvw&x=.25&y=.5&zoom=.1

PS: And do start with plus x meters, I'm sure it'll bring a tear of joy when you see the visual effect that'll give!

**Comment by oscarlorentzon** [comment]
Implemented in a9c8998f2a6352388e75833a0f41759a2df62b06 and 1dc05525e596d89f67a2d014a4df6a5b359d8c55.

**Comment by mrAceT** [comment]
Awesome! Thank you (I think ;)

If you have the time, could you create an example? That would be great (not just for me, but to others also, so they can discover this new possibility/option)
