### ISSUE TITLE
At some sequences clicking on a mapillary image leads to another image

### ISSUE THREAD

**Issue by Lukas458** [mapillary/mapillary-js#309]
### Basic information

**MapillaryJS version**: `...`
**System/Browser**: Windows 10, Microsoft Edge, same issue with firefox and chrome (all newest)

### Steps to Reproduce Behavior

 1. Please have a look at https://www.mapillary.com/app/?lat=52.09678892171618&lng=13.146073642863485&z=16.10213399697147&mapStyle=OpenStreetMap&pKey=GPqiyYjg5ag7-s_0tjbz1g
 2. Look at the sequence which is blue a click on one picture of that sequence, for example one located under Birkenstraße, Luckenwalde
 3. You are leaded to a completely other image. It's from the same sequence but it's an image located somewhere else in the sequence.

### Expected behavior
It should lead to the image which is clicked on

### Actual behavior
It leads to another image of the same sequence

### Additional information
My question would be, what the reason for this is? It occurs only to some sequences, to some others it does not.

I made a video on YouTube to show the problem: https://youtu.be/_OewnAdaUn4

**Comment by oscarlorentzon** [comment]
Thank you for your feedback and for reporting your problem. 

Issues reported in this repository should be specifically related to the library MapillaryJS. This issue is about a general Mapillary feature. Please submit all the information to support@mapillary.com to get support regarding your issue. Thank you.
