### ISSUE TITLE
Web Upload - A server error occured

### ISSUE THREAD

**Issue by teatimetom** [mapillary/mapillary-js#310]
Since two days I try to upload 99 photos via the web uploader. When I click on publish, I get the message: "A server error occured".
I have already tried it several times. I use the browser Firefox, I have already logged in again and deleted cookies and cache. I can't abort the process either, because the uploader only offers publish.

![grafik](https://user-images.githubusercontent.com/57262898/84479876-f0e60d80-ac93-11ea-8834-74a1da7dc66b.png)

**Comment by oscarlorentzon** [comment]
Thank you for your feedback and for reporting your problem. 

Issues reported in this repository should be specifically related to the library MapillaryJS. This issue is about a general Mapillary feature. Please submit all the information to support@mapillary.com to get support regarding your issue. Thank you.
