### ISSUE TITLE
Use in local data

### ISSUE THREAD

**Issue by zpmmehrdad** [mapillary/mapillary-js#328]
Hi,

I have some panoramic images on my disk and I want to load them locally? Can I use it?

Thanks

**Comment by zpmmehrdad** [comment]
@oscarlorentzon Hi,

Is there a way to use it in locally?

**Comment by oscarlorentzon** [comment]
Hi @zpmmehrdad. 

You can visualize any 3D reconstruction dataset and its corresponding images with the MapillaryJS [Data Provider API](https://mapillary.github.io/mapillary-js/classes/dataproviderbase.html) since [v3.0.0](https://github.com/mapillary/mapillary-js/blob/master/CHANGELOG.md#rocket-new-features-1). The dataset can be local or remote.

Take a look at [this PR](https://github.com/mapillary/OpenSfM/pull/698) in [OpenSfM](https://github.com/mapillary/OpenSfM) for a data provider example.

**Comment by zpmmehrdad** [comment]
@oscarlorentzon Hi,

Thanks for the reply, I only have panoramic images. Is this enough?
