### ISSUE TITLE
Is there any way to add your own panorama photos from your own source?

### ISSUE THREAD

**Issue by donnyv** [mapillary/mapillary-js#366]
Are there any examples of using your own panorama photos from your own server?

**Comment by oscarlorentzon** [comment]
Yes, it is possible to write a custom data provider that loads data in any format and converting it to according to the MapillaryJS contract by extending the [`DataProviderBase`](https://mapillary.github.io/mapillary-js/classes/dataproviderbase.html) class and passing it to the [`Viewer` constructor](https://mapillary.github.io/mapillary-js/classes/viewer.html#constructor) as the [`apiClient` option](https://mapillary.github.io/mapillary-js/interfaces/ivieweroptions.html#apiclient).

See the [OpenSfM data provider](https://github.com/mapillary/OpenSfM/blob/master/viewer/mjs/opensfm-data-provider.js) for an example implementation of loading data from a local reconstruction file served from a local server.

**Comment by donnyv** [comment]
Thanks! I'll check that out.

**Comment by donnyv** [comment]
So can I use a regular 360 image for this? Or would I have to break it up into 6 images?

Can I use an image like this?
![8K - RT606-60a552ae7c3a7c859e86fc68](https://user-images.githubusercontent.com/2224189/119674289-166b1900-be0a-11eb-9b25-2a504e3c3e8a.jpg)

**Comment by oscarlorentzon** [comment]
Yes, you can use equirectangular/spherical images. See the guide mentioned above.

**Comment by oscarlorentzon** [comment]
If you just have the images and do not have/want to create any reconstruction data to navigate between the spherical images, I would advise you to use Three.js instead of MapillaryJS.

See https://threejs.org/examples/webgl_panorama_equirectangular.html

**Comment by hvsgrandhi** [comment]
i have followed the steps from: https://github.com/mapillary/mapillary-js/blob/main/src/api/DataProviderBase.ts
i have implemented all the functions mentioned over there.
getCoreImages, getCluster, getSpatialImages, getImages, getImageBuffer, getImageTiles, getMesh, getSequence.
and my street view is visible.(My dataset contains 360degree view images(spherical)).
the problem is the navigation buttons front, back are not visible(there is something which i must have missed) and on using the play button, the transitioning between images is not smooth, it's direct.
I also tried to generate sfm data from opensfm for small set of images, and got reconstruction.json and tried to integrate that data in my data provider, but still something is going wrong and navigation is not enabled.
