### ISSUE TITLE
Add sequence mode to Mapillary

### ISSUE THREAD

**Issue by gyllen** [mapillary/mapillary-js#67]
Cache in sequences instead of tiles

**Comment by oscarlorentzon** [comment]
Related to #191 .

**Comment by oscarlorentzon** [comment]
This is supported by the current graph implementation. Needs to be exposed as a public API.

**Comment by gyllen** [comment]
@oscarlorentzon Can this be a setting?

**Comment by oscarlorentzon** [comment]
@gyllen Does setting mean a viewer options property? In that case it could. It would also have to be a public API method on the `Viewer` so that it can be changed at a later point in time. 

Also, by supported I mean that the graph architecture allows for this to be implemented. There is still a fair amount of work to do though.

**Comment by gyllen** [comment]
@oscarlorentzon Whats your estimate?

**Comment by oscarlorentzon** [comment]
Some days.
